# Generated by Django 4.2.3 on 2023-07-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField(default='0')),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='picture/')),
            ],
        ),
    ]
